type = "card"
title = "Awards"
description = "Honors and awards I have received."

[[items]]
title = "Cum Laude Honor"
subtitle = "The Ohio State University"
date = "2020"
content = "Honored Graduation"

