type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."

[[items]]
title = "BME 343 - Biomedical Engineering Signal and Systems Analysis"
subtitle = "Graduate Teaching Assistant"
date = "Fall 2025"
content = ""
tags = ["Undergraduate", "Senior", "BME"]
