[site]
title = "赵浩君 (Holly Zhao)"
description = "德克萨斯大学奥斯汀分校博士生"
favicon = "/favicon.svg"
last_updated = "2026 年 4 月"

[author]
name = "赵浩君 Holly Zhao"
pronouns = "她/她的"
title = "博士生"
institution = "德克萨斯大学奥斯汀分校"
avatar = "/crop_bio.png"

[social]
# 联系方式（留空或删除以隐藏）

email = "holly.zhao@utexas.edu"
location = "美国 德州 奥斯汀"
location_url = "https://www.google.com/maps/place/The+University+of+Texas+at+Austin+Biomedical+Engineering+(BME)/@30.2893706,-97.7414012,17z/data=!3m1!4b1!4m6!3m5!1s0x8644b5831f0c4335:0xd1b21a4c7b9709a1!8m2!3d30.2893706!4d-97.7388263!16s%2Fg%2F11_tfllvd?entry=ttu&g_ep=EgoyMDI2MDQyNy4wIKXMDSoASAFQAw%3D%3D"
location_details = [
  "R107 W Dean Keeton St",
  "Austin, TX 78712"
]
google_scholar = "https://scholar.google.com/citations?user=C-UIl-AAAAAJ&hl=zh-CN"
orcid = "https://orcid.org/0009-0006-7362-9047"
github = "https://github.com/HollyZhao514"
linkedin = "https://www.linkedin.com/in/holly-zhao/"

[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "论文"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "教学"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "奖项"
type = "page"
target = "awards"
href = "/awards"

# [[navigation]]
# title = "学术服务"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "简历"
type = "page"
target = "cv"
href = "/cv"

[[navigation]]
title = "Toffee"
type = "page"
target = "toffee"
href = "/toffee"
